package com.silvassa.model;
// default package
// Generated Dec 15, 2016 5:54:25 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConstructionTypeMaster generated by hbm2java
 */
@Entity
@Table(name = "construction_type_master", schema = "public")
public class ConstructionTypeMaster implements java.io.Serializable {

	private int constructTypeMasterId;
	private String constructTypeId;
	private String constructTypeDesc;
	private String status;
	private String createdBy;
	private Date createdOn;
	private Date modifiedOn;

	public ConstructionTypeMaster() {
	}

	public ConstructionTypeMaster(int constructTypeMasterId) {
		this.constructTypeMasterId = constructTypeMasterId;
	}

	public ConstructionTypeMaster(int constructTypeMasterId,
			String constructTypeId, String constructTypeDesc, String status,
			String createdBy, Date createdOn, Date modifiedOn) {
		this.constructTypeMasterId = constructTypeMasterId;
		this.constructTypeId = constructTypeId;
		this.constructTypeDesc = constructTypeDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
	}

	@Id
	@Column(name = "construct_type_master_id", unique = true, nullable = false)
	public int getConstructTypeMasterId() {
		return this.constructTypeMasterId;
	}

	public void setConstructTypeMasterId(int constructTypeMasterId) {
		this.constructTypeMasterId = constructTypeMasterId;
	}

	@Column(name = "construct_type_id")
	public String getConstructTypeId() {
		return this.constructTypeId;
	}

	public void setConstructTypeId(String constructTypeId) {
		this.constructTypeId = constructTypeId;
	}

	@Column(name = "construct_type_desc")
	public String getConstructTypeDesc() {
		return this.constructTypeDesc;
	}

	public void setConstructTypeDesc(String constructTypeDesc) {
		this.constructTypeDesc = constructTypeDesc;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "created_on")
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "modified_on")
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

}
