package com.silvassa.model;
// default package
// Generated Dec 15, 2016 5:54:25 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Localitymaster generated by hbm2java
 */
@Entity
@Table(name = "localitymaster", schema = "public")
public class Localitymaster implements java.io.Serializable {

	private int localitymasterId;
	private String localityId;
	private String wardId;
	private String localityName;
	private String status;
	private String createdBy;
	private Date createdOn;
	private Date modifiedOn;

	public Localitymaster() {
	}

	public Localitymaster(int localitymasterId) {
		this.localitymasterId = localitymasterId;
	}

	public Localitymaster(int localitymasterId, String localityId,
			String wardId, String localityName, String status,
			String createdBy, Date createdOn, Date modifiedOn) {
		this.localitymasterId = localitymasterId;
		this.localityId = localityId;
		this.wardId = wardId;
		this.localityName = localityName;
		this.status = status;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
	}

	@Id
	@Column(name = "localitymaster_id", unique = true, nullable = false)
	public int getLocalitymasterId() {
		return this.localitymasterId;
	}

	public void setLocalitymasterId(int localitymasterId) {
		this.localitymasterId = localitymasterId;
	}

	@Column(name = "locality_id")
	public String getLocalityId() {
		return this.localityId;
	}

	public void setLocalityId(String localityId) {
		this.localityId = localityId;
	}

	@Column(name = "ward_id")
	public String getWardId() {
		return this.wardId;
	}

	public void setWardId(String wardId) {
		this.wardId = wardId;
	}

	@Column(name = "locality_name")
	public String getLocalityName() {
		return this.localityName;
	}

	public void setLocalityName(String localityName) {
		this.localityName = localityName;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "created_on")
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "modified_on")
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Localitymaster [localitymasterId=" + localitymasterId
				+ ", localityId=" + localityId + ", wardId=" + wardId
				+ ", localityName=" + localityName + ", status=" + status
				+ ", createdBy=" + createdBy + ", createdOn=" + createdOn
				+ ", modifiedOn=" + modifiedOn + "]";
	}

}
