package com.silvassa.model;
// default package
// Generated Dec 15, 2016 5:54:25 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ObjectionStatusMaster generated by hbm2java
 */
@Entity
@Table(name = "objection_status_master", schema = "public")
public class ObjectionStatusMaster implements java.io.Serializable {

	private int objectionStatusMasterId;
	private String objectionStatusId;
	private String objectionStatusDesc;
	private String status;
	private String createdBy;
	private Date createdOn;
	private Date modifiedOn;

	public ObjectionStatusMaster() {
	}

	public ObjectionStatusMaster(int objectionStatusMasterId) {
		this.objectionStatusMasterId = objectionStatusMasterId;
	}

	public ObjectionStatusMaster(int objectionStatusMasterId,
			String objectionStatusId, String objectionStatusDesc,
			String status, String createdBy, Date createdOn, Date modifiedOn) {
		this.objectionStatusMasterId = objectionStatusMasterId;
		this.objectionStatusId = objectionStatusId;
		this.objectionStatusDesc = objectionStatusDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
	}

	@Id
	@Column(name = "objection_status_master_id", unique = true, nullable = false)
	public int getObjectionStatusMasterId() {
		return this.objectionStatusMasterId;
	}

	public void setObjectionStatusMasterId(int objectionStatusMasterId) {
		this.objectionStatusMasterId = objectionStatusMasterId;
	}

	@Column(name = "objection_status_id")
	public String getObjectionStatusId() {
		return this.objectionStatusId;
	}

	public void setObjectionStatusId(String objectionStatusId) {
		this.objectionStatusId = objectionStatusId;
	}

	@Column(name = "objection_status_desc")
	public String getObjectionStatusDesc() {
		return this.objectionStatusDesc;
	}

	public void setObjectionStatusDesc(String objectionStatusDesc) {
		this.objectionStatusDesc = objectionStatusDesc;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "created_on")
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "modified_on")
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

}
