package com.silvassa.model;
// default package
// Generated Dec 15, 2016 5:54:25 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PropertyOwner generated by hbm2java
 */
@Entity
@Table(name = "property_owner", schema = "public")
public class PropertyOwner implements java.io.Serializable {
    	
        @Id
	@Column(name = "prop_owner_master_id", unique = true, nullable = false)
	private int propOwnerMasterId;
        @Column(name = "prop_owner_id")
	private String propOwnerId;

        
        @Column(name = "property_usage_id")
	private String propertyUsageId;
        @Column(name = "prop_owner_surname")
	private String propOwnerSurname;
        @Column(name = "prop_owner_name")
	private String propOwnerName;
        @Column(name = "prop_owner_aadhar_no")
	private String propOwnerAadharNo;
        @Column(name = "prop_owner_relation_owner")
	private String propOwnerRelationOwner;
	@Column(name = "prop_owner_father_name")
	private String propOwnerFatherName;
	@Column(name = "prop_owner_spouse_name")
	private String propOwnerSpouseName;
	@Column(name = "prop_owner_occupier")
	private String propOwnerOccupier;
	@Column(name = "prop_owner_num_of_person")
	private Long propOwnerNumOfPerson;
	@Column(name = "prop_owner_email_id")
	private String propOwnerEmailId;
	@Column(name = "prop_owner_mobile")
	private String propOwnerMobile;
	@Column(name = "prop_owner_property_cost")
	private String propOwnerPropertyCost;
	@Column(name = "prop_owner_construction_year")
	private String propOwnerConstructionYear;
	@Column(name = "prop_owner_total_floors")
	private String propOwnerTotalFloors;
	@Column(name = "prop_owner_num_of_rooms")
	private String propOwnerNumOfRooms;
	@Column(name = "status")
	private String status;
	@Column(name = "created_by")
	private String createdBy;
	@Temporal(TemporalType.TIME)
	@Column(name = "created_on")
	private Date createdOn;
	@Temporal(TemporalType.TIME)
	@Column(name = "modified_on")
	private Date modifiedOn;
	@Column(name="property_details_id")
	private Integer propertyToOwnerID;
	

	public Integer getPropertyToOwnerID() {
	    return propertyToOwnerID;
	}
	public void setPropertyToOwnerID(Integer propertyToOwnerID) {
	    this.propertyToOwnerID = propertyToOwnerID;
	}
	

	public void setPropOwnerMasterId(int propOwnerMasterId) {
		this.propOwnerMasterId = propOwnerMasterId;
	}

	
	public String getPropOwnerId() {
		return this.propOwnerId;
	}

	public void setPropOwnerId(String propOwnerId) {
		this.propOwnerId = propOwnerId;
	}


	
	public String getPropertyUsageId() {
		return this.propertyUsageId;
	}

	public void setPropertyUsageId(String propertyUsageId) {
		this.propertyUsageId = propertyUsageId;
	}

	
	public String getPropOwnerSurname() {
		return this.propOwnerSurname;
	}

	public void setPropOwnerSurname(String propOwnerSurname) {
		this.propOwnerSurname = propOwnerSurname;
	}

	
	public String getPropOwnerName() {
		return this.propOwnerName;
	}

	public void setPropOwnerName(String propOwnerName) {
		this.propOwnerName = propOwnerName;
	}

	
	public String getPropOwnerAadharNo() {
		return this.propOwnerAadharNo;
	}

	public void setPropOwnerAadharNo(String propOwnerAadharNo) {
		this.propOwnerAadharNo = propOwnerAadharNo;
	}

	
	public String getPropOwnerRelationOwner() {
		return this.propOwnerRelationOwner;
	}

	public void setPropOwnerRelationOwner(String propOwnerRelationOwner) {
		this.propOwnerRelationOwner = propOwnerRelationOwner;
	}

	
	public String getPropOwnerFatherName() {
		return this.propOwnerFatherName;
	}

	public void setPropOwnerFatherName(String propOwnerFatherName) {
		this.propOwnerFatherName = propOwnerFatherName;
	}
	
	public String getPropOwnerSpouseName() {
		return this.propOwnerSpouseName;
	}

	public void setPropOwnerSpouseName(String propOwnerSpouseName) {
		this.propOwnerSpouseName = propOwnerSpouseName;
	}
	
	public String getPropOwnerOccupier() {
		return this.propOwnerOccupier;
	}

	public void setPropOwnerOccupier(String propOwnerOccupier) {
		this.propOwnerOccupier = propOwnerOccupier;
	}
	
	public Long getPropOwnerNumOfPerson() {
		return this.propOwnerNumOfPerson;
	}

	public void setPropOwnerNumOfPerson(Long propOwnerNumOfPerson) {
		this.propOwnerNumOfPerson = propOwnerNumOfPerson;
	}
	
	public String getPropOwnerEmailId() {
		return this.propOwnerEmailId;
	}

	public void setPropOwnerEmailId(String propOwnerEmailId) {
		this.propOwnerEmailId = propOwnerEmailId;
	}
	
	public String getPropOwnerMobile() {
		return this.propOwnerMobile;
	}

	public void setPropOwnerMobile(String propOwnerMobile) {
		this.propOwnerMobile = propOwnerMobile;
	}
	
	public String getPropOwnerPropertyCost() {
		return this.propOwnerPropertyCost;
	}

	public void setPropOwnerPropertyCost(String propOwnerPropertyCost) {
		this.propOwnerPropertyCost = propOwnerPropertyCost;
	}
	
	public String getPropOwnerConstructionYear() {
		return this.propOwnerConstructionYear;
	}

	public void setPropOwnerConstructionYear(String propOwnerConstructionYear) {
		this.propOwnerConstructionYear = propOwnerConstructionYear;
	}
	
	public String getPropOwnerTotalFloors() {
		return this.propOwnerTotalFloors;
	}

	public void setPropOwnerTotalFloors(String propOwnerTotalFloors) {
		this.propOwnerTotalFloors = propOwnerTotalFloors;
	}
	
	public String getPropOwnerNumOfRooms() {
		return this.propOwnerNumOfRooms;
	}

	public void setPropOwnerNumOfRooms(String propOwnerNumOfRooms) {
		this.propOwnerNumOfRooms = propOwnerNumOfRooms;
	}
	
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	
	
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}
	
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

}
