package com.silvassa.model;

// default package
// Generated Jan 27, 2017 4:07:12 PM by Hibernate Tools 4.0.0
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PropertyFloor generated by hbm2java
 */
@Entity
@Table(name = "property_floor", schema = "public")
public class PropertyFloor implements java.io.Serializable {

    //Added By Jay 
    @Id
    @SequenceGenerator(name = "property_floor_pf_id_seq",
            sequenceName = "property_floor_pf_id_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "property_floor_pf_id_seq")
//    @Column(name = "idwebuser", updatable=false)
    @Column(name = "pf_id", unique = true, nullable = false)
    private Integer pfId;
    //Added By Jay End
    @Column(name = "property_unique_id", nullable = false)
    private String propertyUniqueId;
    @Column(name = "property_rentable_id")
    private String propertyRentableId;

    public String getPropertyUniqueId() {
        return propertyUniqueId;
    }

    public void setPropertyUniqueId(String propertyUniqueId) {
        this.propertyUniqueId = propertyUniqueId;
    }
    @Column(name = "pf_floor_name")
    private String pfFloorName;
    @Column(name = "pf_builtup_area", precision = 131089, scale = 0)
    private Double pfBuiltupArea;
    @Column(name = "pf_construction_type")
    private String pfConstructionType;
    @Column(name = "pf_floorwise_build_use")
    private String pfFloorwiseBuildUse;
    @Column(name = "pf_commercial_activity_name")
    private String pfCommercialActivityName;
    @Column(name = "pf_commercial_type")
    private String pfCommercialType;
    @Column(name = "pf_water_pipe_con")
    private String pfWaterPipeCon;
    @Column(name = "pf_water_con_num")
    private String pfWaterConNum;
    @Column(name = "pf_sewerage_con")
    private String pfSewerageCon;
    @Column(name = "pf_sewerage_con_num")
    private String pfSewerageConNum;
    @Column(name = "pf_electric_meter_num")
    private String pfElectricMeterNum;
    @Column(name = "pf_electric_con_num")
    private String pfElectricConNum;
    @Column(name = "pf_cctv_camrea")
    private String pfCctvCamrea;
    @Column(name = "pf_fire_equipment")
    private String pfFireEquipment;
    @Column(name = "pf_lift_available")
    private String pfLiftAvailable;
    @Column(name = "pf_rain_water_harvest")
    private String pfRainWaterHarvest;
    @Column(name = "pf_num_of_borewells")
    private String pfNumOfBorewells;
    @Column(name = "pf_sanitation")
    private String pfSanitation;
    @Column(name = "pf_hording_avail")
    private String pfHordingAvail;
    @Column(name = "pf_mobile_tower")
    private String pfMobileTower;
    @Column(name = "status")
    private String status;
    @Column(name = "created_by")
    private String createdBy;
    @Column(name = "pf_property_subtype")
    private String pf_property_subtype; 
    @Column(name="pf_self_rent")
    private String selfRent;
    @Column(name="pf_annual_rent_value")
    private String annualRent;
    
    
    

    public Integer getPfId() {
        return this.pfId;
    }

    public void setPfId(Integer pfId) {
        this.pfId = pfId;
    }

    public String getPropertyRentableId() {
        return this.propertyRentableId;
    }

    public void setPropertyRentableId(String propertyRentableId) {
        this.propertyRentableId = propertyRentableId;
    }

    public String getPfFloorName() {
        return this.pfFloorName;
    }

    public void setPfFloorName(String pfFloorName) {
        this.pfFloorName = pfFloorName;
    }

    public Double getPfBuiltupArea() {
        return this.pfBuiltupArea;
    }

    public void setPfBuiltupArea(Double pfBuiltupArea) {
        this.pfBuiltupArea = pfBuiltupArea;
    }

    public String getPfConstructionType() {
        return this.pfConstructionType;
    }

    public void setPfConstructionType(String pfConstructionType) {
        this.pfConstructionType = pfConstructionType;
    }

    public String getPfFloorwiseBuildUse() {
        return this.pfFloorwiseBuildUse;
    }

    public void setPfFloorwiseBuildUse(String pfFloorwiseBuildUse) {
        this.pfFloorwiseBuildUse = pfFloorwiseBuildUse;
    }

    public String getPfCommercialActivityName() {
        return this.pfCommercialActivityName;
    }

    public void setPfCommercialActivityName(String pfCommercialActivityName) {
        this.pfCommercialActivityName = pfCommercialActivityName;
    }

    public String getPfCommercialType() {
        return this.pfCommercialType;
    }

    public void setPfCommercialType(String pfCommercialType) {
        this.pfCommercialType = pfCommercialType;
    }

    public String getPfWaterPipeCon() {
        return this.pfWaterPipeCon;
    }

    public void setPfWaterPipeCon(String pfWaterPipeCon) {
        this.pfWaterPipeCon = pfWaterPipeCon;
    }

    public String getPfWaterConNum() {
        return this.pfWaterConNum;
    }

    public void setPfWaterConNum(String pfWaterConNum) {
        this.pfWaterConNum = pfWaterConNum;
    }

    public String getPfSewerageCon() {
        return this.pfSewerageCon;
    }

    public void setPfSewerageCon(String pfSewerageCon) {
        this.pfSewerageCon = pfSewerageCon;
    }

    public String getPfSewerageConNum() {
        return this.pfSewerageConNum;
    }

    public void setPfSewerageConNum(String pfSewerageConNum) {
        this.pfSewerageConNum = pfSewerageConNum;
    }

    public String getPfElectricMeterNum() {
        return this.pfElectricMeterNum;
    }

    public void setPfElectricMeterNum(String pfElectricMeterNum) {
        this.pfElectricMeterNum = pfElectricMeterNum;
    }

    public String getPfElectricConNum() {
        return this.pfElectricConNum;
    }

    public void setPfElectricConNum(String pfElectricConNum) {
        this.pfElectricConNum = pfElectricConNum;
    }

    public String getPfCctvCamrea() {
        return this.pfCctvCamrea;
    }

    public void setPfCctvCamrea(String pfCctvCamrea) {
        this.pfCctvCamrea = pfCctvCamrea;
    }

    public String getPfFireEquipment() {
        return this.pfFireEquipment;
    }

    public void setPfFireEquipment(String pfFireEquipment) {
        this.pfFireEquipment = pfFireEquipment;
    }

    public String getPfLiftAvailable() {
        return this.pfLiftAvailable;
    }

    public void setPfLiftAvailable(String pfLiftAvailable) {
        this.pfLiftAvailable = pfLiftAvailable;
    }

    public String getPfRainWaterHarvest() {
        return this.pfRainWaterHarvest;
    }

    public void setPfRainWaterHarvest(String pfRainWaterHarvest) {
        this.pfRainWaterHarvest = pfRainWaterHarvest;
    }

    public String getPfNumOfBorewells() {
        return this.pfNumOfBorewells;
    }

    public void setPfNumOfBorewells(String pfNumOfBorewells) {
        this.pfNumOfBorewells = pfNumOfBorewells;
    }

    public String getPfSanitation() {
        return this.pfSanitation;
    }

    public void setPfSanitation(String pfSanitation) {
        this.pfSanitation = pfSanitation;
    }

    public String getPfHordingAvail() {
        return this.pfHordingAvail;
    }

    public void setPfHordingAvail(String pfHordingAvail) {
        this.pfHordingAvail = pfHordingAvail;
    }

    public String getPfMobileTower() {
        return this.pfMobileTower;
    }

    public void setPfMobileTower(String pfMobileTower) {
        this.pfMobileTower = pfMobileTower;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    /**
     * @return the pf_property_subtype
     */
    public String getPf_property_subtype() {
        return pf_property_subtype;
    }

    /**
     * @param pf_property_subtype the pf_property_subtype to set
     */
    public void setPf_property_subtype(String pf_property_subtype) {
        this.pf_property_subtype = pf_property_subtype;
    }
   

    /**
     * @return the selfRent
     */
    public String getSelfRent() {
        return selfRent;
    }

    /**
     * @param selfRent the selfRent to set
     */
    public void setSelfRent(String selfRent) {
        this.selfRent = selfRent;
    }

    /**
     * @return the annualRent
     */
    public String getAnnualRent() {
        return annualRent;
    }

    /**
     * @param annualRent the annualRent to set
     */
    public void setAnnualRent(String annualRent) {
        this.annualRent = annualRent;
    }

    @Override
    public String toString() {
        return "PropertyFloor{" + "pfId=" + pfId + ", propertyUniqueId=" + propertyUniqueId + ", propertyRentableId=" + propertyRentableId + ", pfFloorName=" + pfFloorName + ", pfBuiltupArea=" + pfBuiltupArea + ", pfConstructionType=" + pfConstructionType + ", pfFloorwiseBuildUse=" + pfFloorwiseBuildUse + ", pfCommercialActivityName=" + pfCommercialActivityName + ", pfCommercialType=" + pfCommercialType + ", pfWaterPipeCon=" + pfWaterPipeCon + ", pfWaterConNum=" + pfWaterConNum + ", pfSewerageCon=" + pfSewerageCon + ", pfSewerageConNum=" + pfSewerageConNum + ", pfElectricMeterNum=" + pfElectricMeterNum + ", pfElectricConNum=" + pfElectricConNum + ", pfCctvCamrea=" + pfCctvCamrea + ", pfFireEquipment=" + pfFireEquipment + ", pfLiftAvailable=" + pfLiftAvailable + ", pfRainWaterHarvest=" + pfRainWaterHarvest + ", pfNumOfBorewells=" + pfNumOfBorewells + ", pfSanitation=" + pfSanitation + ", pfHordingAvail=" + pfHordingAvail + ", pfMobileTower=" + pfMobileTower + ", status=" + status + ", createdBy=" + createdBy + ", pf_property_subtype=" + pf_property_subtype + ", selfRent=" + selfRent + ", annualRent=" + annualRent + '}';
    }

}
