package com.silvassa.model;
// default package
// Generated Dec 15, 2016 5:54:25 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PropertyUsageMaster generated by hbm2java
 */
@Entity
@Table(name = "property_usage_master", schema = "public")
public class PropertyUsageMaster implements java.io.Serializable {

	private int propertyUsageMasterId;
	private String propertyUsageId;
	private String propertyTypeId;
	private String propertyUsageDetails;
	private String status;
	private String createdBy;
	private Date createdOn;
	private Date modifiedOn;

	public PropertyUsageMaster() {
	}

	public PropertyUsageMaster(int propertyUsageMasterId) {
		this.propertyUsageMasterId = propertyUsageMasterId;
	}

	public PropertyUsageMaster(int propertyUsageMasterId,
			String propertyUsageId, String propertyTypeId,
			String propertyUsageDetails, String status, String createdBy,
			Date createdOn, Date modifiedOn) {
		this.propertyUsageMasterId = propertyUsageMasterId;
		this.propertyUsageId = propertyUsageId;
		this.propertyTypeId = propertyTypeId;
		this.propertyUsageDetails = propertyUsageDetails;
		this.status = status;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
	}

	@Id
	@Column(name = "property_usage_master_id", unique = true, nullable = false)
	public int getPropertyUsageMasterId() {
		return this.propertyUsageMasterId;
	}

	public void setPropertyUsageMasterId(int propertyUsageMasterId) {
		this.propertyUsageMasterId = propertyUsageMasterId;
	}

	@Column(name = "property_usage_id")
	public String getPropertyUsageId() {
		return this.propertyUsageId;
	}

	public void setPropertyUsageId(String propertyUsageId) {
		this.propertyUsageId = propertyUsageId;
	}

	@Column(name = "property_type_id")
	public String getPropertyTypeId() {
		return this.propertyTypeId;
	}

	public void setPropertyTypeId(String propertyTypeId) {
		this.propertyTypeId = propertyTypeId;
	}

	@Column(name = "property_usage_details")
	public String getPropertyUsageDetails() {
		return this.propertyUsageDetails;
	}

	public void setPropertyUsageDetails(String propertyUsageDetails) {
		this.propertyUsageDetails = propertyUsageDetails;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "created_on")
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "modified_on")
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

}
