package com.silvassa.model;

// default package
// Generated Jan 25, 2017 12:11:01 PM by Hibernate Tools 4.0.0
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * PropertyDetails generated by hbm2java
 */
@Entity
@Table(name = "property_details")
public class PropertyDetails implements java.io.Serializable {

    private String propertyUniqueId;
    private Integer propertyDetailsId;
    private String zoneId;
    private String ward;
    private String propertySurveyId;
    private String propertyParcelId;
    private String propertyGridNo;
    private String propertyOldSmcPropTaxNum;
    private String propertyPhotoId;
    private String propertyCameraNum;
    private String propertySurveyNum;
    private String propertyPlotNum;
    private String propertyHouseNo;
    private String propertyBuildingName;
    private String propertySublocality;
    private String propertyLandmark;
    private String propertyRoad;
    private String propertyCity;
    private String propertyPincode;
    private String propertyConstructionYear;
    private String propertyCost;
    private String propertyContact;
    private String propertyOwner;
    private String propertyOwnerFather;
    private String propertyOwnerSpouse;
    private String propertyAadharNum;
    private String propertyOwnerEmail;
    private String propertyLocality;
    private String propertyType;
    private String propertyStatus;
    private String propertyOccupierName;
    private String propertyRelationOwner;
    private String propertyTotalFloor;
    private String propertySurveyedFloor;
    private String propertyPlotArea;
    private String propertyNumOfRooms;
    private String propertyNumOfPersons;
    private Integer propertyMale18Plus;
    private Integer propertyFem18Plus;
    private Integer propertyMale18Minus;
    private Integer propertyFem18Minus;
    private String propertyName1;
    private String propertyName2;
    private String propertyName3;
    private String propertyName4;
    private String propertyName5;
    private String propertyName6;
    private String propertyRoomCntHotel;
    private String propertyRoomCntSchoolClg;
    private String propertyRoomCntHostel;
    private String propertyRoomCntHospiNurse;
    private String propertyLatitude;
    private String propertyLongitude;
    private String status;
    private String createdBy;
    private String modifiedBy;
    private String completeAddress;
    private Date  createdOn;
    private String property_category_desc;
    private String ownerSex;
    private String occupierSex;
    private String propertyOwnerCorrespAddr;
    private String occupoerFather;
    private String occupierMobile;
    private String occupierEmail;
    private String occupierAadharNo;
    private String smcSurveyNo;
    private String smcPlotNo;
    private String shopNo;
    
    
    
    
    

//    @Transient
//    private List<PropertyFloor> pFloor;
//
//    public List<PropertyFloor> getpFloor() {
//        return pFloor;
//    }
//
//    public void setpFloor(List<PropertyFloor> pFloor) {
//        this.pFloor = pFloor;
//    }

    @Column(name = "ward", nullable = true)
    public String getWard() {
        return ward;
    }

    public void setWard(String ward) {
        this.ward = ward;
    }

    @Id
    @Column(name = "property_unique_id", unique = true, nullable = false)
    public String getPropertyUniqueId() {
        return this.propertyUniqueId;
    }

    public void setPropertyUniqueId(String propertyUniqueId) {
        this.propertyUniqueId = propertyUniqueId;
    }

    @Generated(GenerationTime.ALWAYS)
    @Column(name = "property_details_id", nullable = false)
    public Integer getPropertyDetailsId() {
        return this.propertyDetailsId;
    }

    public void setPropertyDetailsId(Integer propertyDetailsId) {
        this.propertyDetailsId = propertyDetailsId;
    }

    @Column(name = "zone_id")
    public String getZoneId() {
        return this.zoneId;
    }

    public void setZoneId(String zoneId) {
        this.zoneId = zoneId;
    }

    @Column(name = "property_survey_id")
    public String getPropertySurveyId() {
        return this.propertySurveyId;
    }

    public void setPropertySurveyId(String propertySurveyId) {
        this.propertySurveyId = propertySurveyId;
    }

    @Column(name = "property_parcel_id")
    public String getPropertyParcelId() {
        return this.propertyParcelId;
    }

    public void setPropertyParcelId(String propertyParcelId) {
        this.propertyParcelId = propertyParcelId;
    }

    @Column(name = "property_grid_no")
    public String getPropertyGridNo() {
        return this.propertyGridNo;
    }

    public void setPropertyGridNo(String propertyGridNo) {
        this.propertyGridNo = propertyGridNo;
    }

    @Column(name = "property_old_smc_prop_tax_num")
    public String getPropertyOldSmcPropTaxNum() {
        return this.propertyOldSmcPropTaxNum;
    }

    public void setPropertyOldSmcPropTaxNum(String propertyOldSmcPropTaxNum) {
        this.propertyOldSmcPropTaxNum = propertyOldSmcPropTaxNum;
    }

    @Column(name = "property_photo_id")
    public String getPropertyPhotoId() {
        return this.propertyPhotoId;
    }

    public void setPropertyPhotoId(String propertyPhotoId) {
        this.propertyPhotoId = propertyPhotoId;
    }

    @Column(name = "property_camera_num")
    public String getPropertyCameraNum() {
        return this.propertyCameraNum;
    }

    public void setPropertyCameraNum(String propertyCameraNum) {
        this.propertyCameraNum = propertyCameraNum;
    }

    @Column(name = "property_survey_num")
    public String getPropertySurveyNum() {
        return this.propertySurveyNum;
    }

    public void setPropertySurveyNum(String propertySurveyNum) {
        this.propertySurveyNum = propertySurveyNum;
    }

    @Column(name = "property_plot_num")
    public String getPropertyPlotNum() {
        return this.propertyPlotNum;
    }

    public void setPropertyPlotNum(String propertyPlotNum) {
        this.propertyPlotNum = propertyPlotNum;
    }

    @Column(name = "property_house_no")
    public String getPropertyHouseNo() {
        return this.propertyHouseNo;
    }

    public void setPropertyHouseNo(String propertyHouseNo) {
        this.propertyHouseNo = propertyHouseNo;
    }

    @Column(name = "property_building_name")
    public String getPropertyBuildingName() {
        return this.propertyBuildingName;
    }

    public void setPropertyBuildingName(String propertyBuildingName) {
        this.propertyBuildingName = propertyBuildingName;
    }

    @Column(name = "property_sublocality")
    public String getPropertySublocality() {
        return this.propertySublocality;
    }

    public void setPropertySublocality(String propertySublocality) {
        this.propertySublocality = propertySublocality;
    }

    @Column(name = "property_landmark")
    public String getPropertyLandmark() {
        return this.propertyLandmark;
    }

    public void setPropertyLandmark(String propertyLandmark) {
        this.propertyLandmark = propertyLandmark;
    }

    @Column(name = "property_road")
    public String getPropertyRoad() {
        return this.propertyRoad;
    }

    public void setPropertyRoad(String propertyRoad) {
        this.propertyRoad = propertyRoad;
    }

    @Column(name = "property_city")
    public String getPropertyCity() {
        return this.propertyCity;
    }

    public void setPropertyCity(String propertyCity) {
        this.propertyCity = propertyCity;
    }

    @Column(name = "property_pincode")
    public String getPropertyPincode() {
        return this.propertyPincode;
    }

    public void setPropertyPincode(String propertyPincode) {
        this.propertyPincode = propertyPincode;
    }

    @Column(name = "property_construction_year")
    public String getPropertyConstructionYear() {
        return this.propertyConstructionYear;
    }

    public void setPropertyConstructionYear(String propertyConstructionYear) {
        this.propertyConstructionYear = propertyConstructionYear;
    }

    @Column(name = "property_cost")
    public String getPropertyCost() {
        return this.propertyCost;
    }

    public void setPropertyCost(String propertyCost) {
        this.propertyCost = propertyCost;
    }

    @Column(name = "property_contact")
    public String getPropertyContact() {
        return this.propertyContact;
    }

    public void setPropertyContact(String propertyContact) {
        this.propertyContact = propertyContact;
    }

    @Column(name = "property_owner")
    public String getPropertyOwner() {
        return this.propertyOwner;
    }

    public void setPropertyOwner(String propertyOwner) {
        this.propertyOwner = propertyOwner;
    }

    @Column(name = "property_owner_father")
    public String getPropertyOwnerFather() {
        return this.propertyOwnerFather;
    }

    public void setPropertyOwnerFather(String propertyOwnerFather) {
        this.propertyOwnerFather = propertyOwnerFather;
    }

    @Column(name = "property_owner_spouse")
    public String getPropertyOwnerSpouse() {
        return this.propertyOwnerSpouse;
    }

    public void setPropertyOwnerSpouse(String propertyOwnerSpouse) {
        this.propertyOwnerSpouse = propertyOwnerSpouse;
    }

    @Column(name = "property_aadhar_num")
    public String getPropertyAadharNum() {
        return this.propertyAadharNum;
    }

    public void setPropertyAadharNum(String propertyAadharNum) {
        this.propertyAadharNum = propertyAadharNum;
    }

    @Column(name = "property_owner_email")
    public String getPropertyOwnerEmail() {
        return this.propertyOwnerEmail;
    }

    public void setPropertyOwnerEmail(String propertyOwnerEmail) {
        this.propertyOwnerEmail = propertyOwnerEmail;
    }

    @Column(name = "property_occupier_name")
    public String getPropertyOccupierName() {
        return this.propertyOccupierName;
    }

    public void setPropertyOccupierName(String propertyOccupierName) {
        this.propertyOccupierName = propertyOccupierName;
    }

    @Column(name = "property_relation_owner")
    public String getPropertyRelationOwner() {
        return this.propertyRelationOwner;
    }

    public void setPropertyRelationOwner(String propertyRelationOwner) {
        this.propertyRelationOwner = propertyRelationOwner;
    }

    @Column(name = "property_total_floor")
    public String getPropertyTotalFloor() {
        return this.propertyTotalFloor;
    }

    public void setPropertyTotalFloor(String propertyTotalFloor) {
        this.propertyTotalFloor = propertyTotalFloor;
    }

    @Column(name = "property_surveyed_floor")
    public String getPropertySurveyedFloor() {
        return this.propertySurveyedFloor;
    }

    public void setPropertySurveyedFloor(String propertySurveyedFloor) {
        this.propertySurveyedFloor = propertySurveyedFloor;
    }

    @Column(name = "property_plot_area")
    public String getPropertyPlotArea() {
        return this.propertyPlotArea;
    }

    public void setPropertyPlotArea(String propertyPlotArea) {
        this.propertyPlotArea = propertyPlotArea;
    }

    @Column(name = "property_num_of_rooms")
    public String getPropertyNumOfRooms() {
        return this.propertyNumOfRooms;
    }

    public void setPropertyNumOfRooms(String propertyNumOfRooms) {
        this.propertyNumOfRooms = propertyNumOfRooms;
    }

    @Column(name = "property_num_of_persons")
    public String getPropertyNumOfPersons() {
        return this.propertyNumOfPersons;
    }

    public void setPropertyNumOfPersons(String propertyNumOfPersons) {
        this.propertyNumOfPersons = propertyNumOfPersons;
    }

    @Column(name = "property_male_18_plus", precision = 131089, scale = 0)
    public Integer getPropertyMale18Plus() {
        return this.propertyMale18Plus;
    }

    public void setPropertyMale18Plus(Integer propertyMale18Plus) {
        this.propertyMale18Plus = propertyMale18Plus;
    }

    @Column(name = "property_fem_18_plus", precision = 131089, scale = 0)
    public Integer getPropertyFem18Plus() {
        return this.propertyFem18Plus;
    }

    public void setPropertyFem18Plus(Integer propertyFem18Plus) {
        this.propertyFem18Plus = propertyFem18Plus;
    }

    @Column(name = "property_male_18_minus", precision = 131089, scale = 0)
    public Integer getPropertyMale18Minus() {
        return this.propertyMale18Minus;
    }

    public void setPropertyMale18Minus(Integer propertyMale18Minus) {
        this.propertyMale18Minus = propertyMale18Minus;
    }

    @Column(name = "property_fem_18_minus", precision = 131089, scale = 0)
    public Integer getPropertyFem18Minus() {
        return this.propertyFem18Minus;
    }

    public void setPropertyFem18Minus(Integer propertyFem18Minus) {
        this.propertyFem18Minus = propertyFem18Minus;
    }

    @Column(name = "property_name1")
    public String getPropertyName1() {
        return this.propertyName1;
    }

    public void setPropertyName1(String propertyName1) {
        this.propertyName1 = propertyName1;
    }

    @Column(name = "property_name2")
    public String getPropertyName2() {
        return this.propertyName2;
    }

    public void setPropertyName2(String propertyName2) {
        this.propertyName2 = propertyName2;
    }

    @Column(name = "property_name3")
    public String getPropertyName3() {
        return this.propertyName3;
    }

    public void setPropertyName3(String propertyName3) {
        this.propertyName3 = propertyName3;
    }

    @Column(name = "property_name4")
    public String getPropertyName4() {
        return this.propertyName4;
    }

    public void setPropertyName4(String propertyName4) {
        this.propertyName4 = propertyName4;
    }

    @Column(name = "property_name5")
    public String getPropertyName5() {
        return this.propertyName5;
    }

    public void setPropertyName5(String propertyName5) {
        this.propertyName5 = propertyName5;
    }

    @Column(name = "property_name6")
    public String getPropertyName6() {
        return this.propertyName6;
    }

    public void setPropertyName6(String propertyName6) {
        this.propertyName6 = propertyName6;
    }

    @Column(name = "property_room_cnt_hotel")
    public String getPropertyRoomCntHotel() {
        return this.propertyRoomCntHotel;
    }

    public void setPropertyRoomCntHotel(String propertyRoomCntHotel) {
        this.propertyRoomCntHotel = propertyRoomCntHotel;
    }

    @Column(name = "property_room_cnt_school_clg")
    public String getPropertyRoomCntSchoolClg() {
        return this.propertyRoomCntSchoolClg;
    }

    public void setPropertyRoomCntSchoolClg(String propertyRoomCntSchoolClg) {
        this.propertyRoomCntSchoolClg = propertyRoomCntSchoolClg;
    }

    @Column(name = "property_room_cnt_hostel")
    public String getPropertyRoomCntHostel() {
        return this.propertyRoomCntHostel;
    }

    public void setPropertyRoomCntHostel(String propertyRoomCntHostel) {
        this.propertyRoomCntHostel = propertyRoomCntHostel;
    }

    @Column(name = "property_room_cnt_hospi_nurse")
    public String getPropertyRoomCntHospiNurse() {
        return this.propertyRoomCntHospiNurse;
    }

    public void setPropertyRoomCntHospiNurse(String propertyRoomCntHospiNurse) {
        this.propertyRoomCntHospiNurse = propertyRoomCntHospiNurse;
    }

    @Column(name = "property_latitude")
    public String getPropertyLatitude() {
        return this.propertyLatitude;
    }

    public void setPropertyLatitude(String propertyLatitude) {
        this.propertyLatitude = propertyLatitude;
    }

    @Column(name = "property_longitude")
    public String getPropertyLongitude() {
        return this.propertyLongitude;
    }

    public void setPropertyLongitude(String propertyLongitude) {
        this.propertyLongitude = propertyLongitude;
    }

    @Column(name = "status")
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "created_by")
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "modified_by")
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on")
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "property_type")
    public String getPropertyType() {
        return propertyType;
    }

    /**
     * @param propertyType the propertyType to set
     */
    public void setPropertyType(String propertyType) {
        this.propertyType = propertyType;
    }

    @Column(name = "property_locality")
    public String getPropertyLocality() {
        return propertyLocality;
    }

    /**
     * @param propertyLocality the propertyLocality to set
     */
    public void setPropertyLocality(String propertyLocality) {
        this.propertyLocality = propertyLocality;
    }

    @Column(name = "property_present_status", insertable = false, updatable = false)
    public String getPropertyStatus() {
        return propertyStatus;
    }

    public void setPropertyStatus(String propertyStatus) {
        this.propertyStatus = propertyStatus;
    }

    @Column(name = "complete_address")
    public String getCompleteAddress() {
        return completeAddress;
    }

    public void setCompleteAddress(String completeAddress) {
        this.completeAddress = completeAddress;
    }

    /**
     * @return the property_category_desc
     */
    @Column(name = "property_category_desc")
    public String getProperty_category_desc() {
        return property_category_desc;
    }

    /**
     * @param property_category_desc the property_category_desc to set
     */
    public void setProperty_category_desc(String property_category_desc) {
        this.property_category_desc = property_category_desc;
    }

    @Override
    public String toString() {
        return "PropertyDetails{" + "propertyUniqueId=" + propertyUniqueId + ", propertyDetailsId=" + propertyDetailsId + ", zoneId=" + zoneId + ", ward=" + ward + ", propertySurveyId=" + propertySurveyId + ", propertyParcelId=" + propertyParcelId + ", propertyGridNo=" + propertyGridNo + ", propertyOldSmcPropTaxNum=" + propertyOldSmcPropTaxNum + ", propertyPhotoId=" + propertyPhotoId + ", propertyCameraNum=" + propertyCameraNum + ", propertySurveyNum=" + propertySurveyNum + ", propertyPlotNum=" + propertyPlotNum + ", propertyHouseNo=" + propertyHouseNo + ", propertyBuildingName=" + propertyBuildingName + ", propertySublocality=" + propertySublocality + ", propertyLandmark=" + propertyLandmark + ", propertyRoad=" + propertyRoad + ", propertyCity=" + propertyCity + ", propertyPincode=" + propertyPincode + ", propertyConstructionYear=" + propertyConstructionYear + ", propertyCost=" + propertyCost + ", propertyContact=" + propertyContact + ", propertyOwner=" + propertyOwner + ", propertyOwnerFather=" + propertyOwnerFather + ", propertyOwnerSpouse=" + propertyOwnerSpouse + ", propertyAadharNum=" + propertyAadharNum + ", propertyOwnerEmail=" + propertyOwnerEmail + ", propertyLocality=" + propertyLocality + ", propertyType=" + propertyType + ", propertyStatus=" + propertyStatus + ", propertyOccupierName=" + propertyOccupierName + ", propertyRelationOwner=" + propertyRelationOwner + ", propertyTotalFloor=" + propertyTotalFloor + ", propertySurveyedFloor=" + propertySurveyedFloor + ", propertyPlotArea=" + propertyPlotArea + ", propertyNumOfRooms=" + propertyNumOfRooms + ", propertyNumOfPersons=" + propertyNumOfPersons + ", propertyMale18Plus=" + propertyMale18Plus + ", propertyFem18Plus=" + propertyFem18Plus + ", propertyMale18Minus=" + propertyMale18Minus + ", propertyFem18Minus=" + propertyFem18Minus + ", propertyName1=" + propertyName1 + ", propertyName2=" + propertyName2 + ", propertyName3=" + propertyName3 + ", propertyName4=" + propertyName4 + ", propertyName5=" + propertyName5 + ", propertyName6=" + propertyName6 + ", propertyRoomCntHotel=" + propertyRoomCntHotel + ", propertyRoomCntSchoolClg=" + propertyRoomCntSchoolClg + ", propertyRoomCntHostel=" + propertyRoomCntHostel + ", propertyRoomCntHospiNurse=" + propertyRoomCntHospiNurse + ", propertyLatitude=" + propertyLatitude + ", propertyLongitude=" + propertyLongitude + ", status=" + status + ", createdBy=" + createdBy + ", modifiedBy=" + modifiedBy + ", completeAddress=" + completeAddress + ", createdOn=" + createdOn + ", property_category_desc=" + property_category_desc + '}';
    }

    /**
     * @return the ownerSex
     */
    @Column(name = "owner_sex")
    public String getOwnerSex() {
        return ownerSex;
    }

    /**
     * @param ownerSex the ownerSex to set
     */
    public void setOwnerSex(String ownerSex) {
        this.ownerSex = ownerSex;
    }

    /**
     * @return the occupierSex
     */
    @Column(name = "occupier_sex")
    public String getOccupierSex() {
        return occupierSex;
    }

    /**
     * @param occupierSex the occupierSex to set
     */
    public void setOccupierSex(String occupierSex) {
        this.occupierSex = occupierSex;
    }

    /**
     * @return the propertyOwnerCorrespAddr
     */
    @Column(name = "property_owner_address")
    public String getPropertyOwnerCorrespAddr() {
        return propertyOwnerCorrespAddr;
    }

    /**
     * @param propertyOwnerCorrespAddr the propertyOwnerCorrespAddr to set
     */
    public void setPropertyOwnerCorrespAddr(String propertyOwnerCorrespAddr) {
        this.propertyOwnerCorrespAddr = propertyOwnerCorrespAddr;
    }

    /**
     * @return the occupoerFather
     */
    @Column(name = "occupier_father")
    public String getOccupoerFather() {
        return occupoerFather;
    }

    /**
     * @param occupoerFather the occupoerFather to set
     */
    public void setOccupoerFather(String occupoerFather) {
        this.occupoerFather = occupoerFather;
    }

    /**
     * @return the occupierMobile
     */
    @Column(name = "occupier_contactno")
    public String getOccupierMobile() {
        return occupierMobile;
    }

    /**
     * @param occupierMobile the occupierMobile to set
     */
    public void setOccupierMobile(String occupierMobile) {
        this.occupierMobile = occupierMobile;
    }

    /**
     * @return the occupierEmail
     */
    @Column(name = "occupier_email")
    public String getOccupierEmail() {
        return occupierEmail;
    }

    /**
     * @param occupierEmail the occupierEmail to set
     */
    public void setOccupierEmail(String occupierEmail) {
        this.occupierEmail = occupierEmail;
    }

    /**
     * @return the occupierAadharNo
     */
    @Column(name = "occupier_aadhar_no")
    public String getOccupierAadharNo() {
        return occupierAadharNo;
    }

    /**
     * @param occupierAadharNo the occupierAadharNo to set
     */
    public void setOccupierAadharNo(String occupierAadharNo) {
        this.occupierAadharNo = occupierAadharNo;
    }

    /**
     * @return the smcSurveyNo
     */
     @Column(name = "smc_survey_no")
    public String getSmcSurveyNo() {
        return smcSurveyNo;
    }

    /**
     * @param smcSurveyNo the smcSurveyNo to set
     */
    public void setSmcSurveyNo(String smcSurveyNo) {
        this.smcSurveyNo = smcSurveyNo;
    }

    /**
     * @return the smcPlotNo
     */
    @Column(name = "smc_plot_no")
    public String getSmcPlotNo() {
        return smcPlotNo;
    }

    /**
     * @param smcPlotNo the smcPlotNo to set
     */
    public void setSmcPlotNo(String smcPlotNo) {
        this.smcPlotNo = smcPlotNo;
    }
   
   

    /**
     * @return the shopNo
     */
    @Column(name="shop_no")
    public String getShopNo() {
        return shopNo;
    }

    /**
     * @param shopNo the shopNo to set
     */
    public void setShopNo(String shopNo) {
        this.shopNo = shopNo;
    }
    
}
