// default package
// Generated Jan 27, 2017 4:07:12 PM by Hibernate Tools 4.0.0
package com.silvassa.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rolemaster generated by hbm2java
 */
@Entity
@Table(name = "rolemaster", schema = "public")
public class Rolemaster implements java.io.Serializable {

	private int rolemasterId;
	private String roleId;
	private String roleName;
	private String status;
	private String createdBy;
	private Date createdOn;
	private Date modifiedOn;

	public Rolemaster() {
	}

	public Rolemaster(int rolemasterId) {
		this.rolemasterId = rolemasterId;
	}

	public Rolemaster(int rolemasterId, String roleId, String roleName,
			String status, String createdBy, Date createdOn, Date modifiedOn) {
		this.rolemasterId = rolemasterId;
		this.roleId = roleId;
		this.roleName = roleName;
		this.status = status;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
	}

	@Id
	@Column(name = "rolemaster_id", unique = true, nullable = false)
	public int getRolemasterId() {
		return this.rolemasterId;
	}

	public void setRolemasterId(int rolemasterId) {
		this.rolemasterId = rolemasterId;
	}

	@Column(name = "role_id")
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name")
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "created_on")
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "modified_on")
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

}
