package com.silvassa.model;

// default package
// Generated Feb 14, 2017 3:48:29 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaxdetailsviewId generated by hbm2java
 */
@Embeddable
public class TaxdetailsviewId implements java.io.Serializable {

	private Long rowNumber;
	private String taxNo;
	private String objectionStatus;
	private String propertyUniqueId;
	private String taxAmount;
	private String financialYear;
	private String noticeGenerated;

	public TaxdetailsviewId() {
	}

	public TaxdetailsviewId(Long rowNumber, String taxNo,
			String objectionStatus, String propertyUniqueId, String taxAmount,
			String financialYear, String noticeGenerated) {
		this.rowNumber = rowNumber;
		this.taxNo = taxNo;
		this.objectionStatus = objectionStatus;
		this.propertyUniqueId = propertyUniqueId;
		this.taxAmount = taxAmount;
		this.financialYear = financialYear;
		this.noticeGenerated = noticeGenerated;
	}

	@Column(name = "row_number")
	public Long getRowNumber() {
		return this.rowNumber;
	}

	public void setRowNumber(Long rowNumber) {
		this.rowNumber = rowNumber;
	}

	@Column(name = "tax_no")
	public String getTaxNo() {
		return this.taxNo;
	}

	public void setTaxNo(String taxNo) {
		this.taxNo = taxNo;
	}

	@Column(name = "objection_status")
	public String getObjectionStatus() {
		return this.objectionStatus;
	}

	public void setObjectionStatus(String objectionStatus) {
		this.objectionStatus = objectionStatus;
	}

	@Column(name = "property_unique_id")
	public String getPropertyUniqueId() {
		return this.propertyUniqueId;
	}

	public void setPropertyUniqueId(String propertyUniqueId) {
		this.propertyUniqueId = propertyUniqueId;
	}

	@Column(name = "tax_amount")
	public String getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(String taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "financial_year")
	public String getFinancialYear() {
		return this.financialYear;
	}

	public void setFinancialYear(String financialYear) {
		this.financialYear = financialYear;
	}

	@Column(name = "notice_generated")
	public String getNoticeGenerated() {
		return this.noticeGenerated;
	}

	public void setNoticeGenerated(String noticeGenerated) {
		this.noticeGenerated = noticeGenerated;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaxdetailsviewId))
			return false;
		TaxdetailsviewId castOther = (TaxdetailsviewId) other;

		return ((this.getRowNumber() == castOther.getRowNumber()) || (this
				.getRowNumber() != null && castOther.getRowNumber() != null && this
				.getRowNumber().equals(castOther.getRowNumber())))
				&& ((this.getTaxNo() == castOther.getTaxNo()) || (this
						.getTaxNo() != null && castOther.getTaxNo() != null && this
						.getTaxNo().equals(castOther.getTaxNo())))
				&& ((this.getObjectionStatus() == castOther
						.getObjectionStatus()) || (this.getObjectionStatus() != null
						&& castOther.getObjectionStatus() != null && this
						.getObjectionStatus().equals(
								castOther.getObjectionStatus())))
				&& ((this.getPropertyUniqueId() == castOther
						.getPropertyUniqueId()) || (this.getPropertyUniqueId() != null
						&& castOther.getPropertyUniqueId() != null && this
						.getPropertyUniqueId().equals(
								castOther.getPropertyUniqueId())))
				&& ((this.getTaxAmount() == castOther.getTaxAmount()) || (this
						.getTaxAmount() != null
						&& castOther.getTaxAmount() != null && this
						.getTaxAmount().equals(castOther.getTaxAmount())))
				&& ((this.getFinancialYear() == castOther.getFinancialYear()) || (this
						.getFinancialYear() != null
						&& castOther.getFinancialYear() != null && this
						.getFinancialYear()
						.equals(castOther.getFinancialYear())))
				&& ((this.getNoticeGenerated() == castOther
						.getNoticeGenerated()) || (this.getNoticeGenerated() != null
						&& castOther.getNoticeGenerated() != null && this
						.getNoticeGenerated().equals(
								castOther.getNoticeGenerated())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRowNumber() == null ? 0 : this.getRowNumber().hashCode());
		result = 37 * result
				+ (getTaxNo() == null ? 0 : this.getTaxNo().hashCode());
		result = 37
				* result
				+ (getObjectionStatus() == null ? 0 : this.getObjectionStatus()
						.hashCode());
		result = 37
				* result
				+ (getPropertyUniqueId() == null ? 0 : this
						.getPropertyUniqueId().hashCode());
		result = 37 * result
				+ (getTaxAmount() == null ? 0 : this.getTaxAmount().hashCode());
		result = 37
				* result
				+ (getFinancialYear() == null ? 0 : this.getFinancialYear()
						.hashCode());
		result = 37
				* result
				+ (getNoticeGenerated() == null ? 0 : this.getNoticeGenerated()
						.hashCode());
		return result;
	}

}
