package com.silvassa.model;

// default package
// Generated Feb 14, 2017 3:48:29 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Taxdetailsview generated by hbm2java
 */
@Entity
@Table(name = "taxdetailsview", schema = "public")
public class Taxdetailsview implements java.io.Serializable {

	private TaxdetailsviewId id;

	public Taxdetailsview() {
	}

	public Taxdetailsview(TaxdetailsviewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "rowNumber", column = @Column(name = "row_number")),
			@AttributeOverride(name = "taxNo", column = @Column(name = "tax_no")),
			@AttributeOverride(name = "objectionStatus", column = @Column(name = "objection_status")),
			@AttributeOverride(name = "propertyUniqueId", column = @Column(name = "property_unique_id")),
			@AttributeOverride(name = "taxAmount", column = @Column(name = "grand_total")),
			@AttributeOverride(name = "financialYear", column = @Column(name = "financial_year")),
			@AttributeOverride(name = "noticeGenerated", column = @Column(name = "notice_generated")) })
	public TaxdetailsviewId getId() {
		return this.id;
	}

	public void setId(TaxdetailsviewId id) {
		this.id = id;
	}

}
