// default package
// Generated Jan 27, 2017 4:07:12 PM by Hibernate Tools 4.0.0
package com.silvassa.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaxGeneratedLogId generated by hbm2java
 */
@Embeddable
public class TaxGeneratedLogId implements java.io.Serializable {

	private int id;
	private String generatedby;
	private String generatedon;
	private String zoneid;
	private Date generatedyear;

	public TaxGeneratedLogId() {
	}

	public TaxGeneratedLogId(int id) {
		this.id = id;
	}

	public TaxGeneratedLogId(int id, String generatedby, String generatedon,
			String zoneid, Date generatedyear) {
		this.id = id;
		this.generatedby = generatedby;
		this.generatedon = generatedon;
		this.zoneid = zoneid;
		this.generatedyear = generatedyear;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "generatedby")
	public String getGeneratedby() {
		return this.generatedby;
	}

	public void setGeneratedby(String generatedby) {
		this.generatedby = generatedby;
	}

	@Column(name = "generatedon")
	public String getGeneratedon() {
		return this.generatedon;
	}

	public void setGeneratedon(String generatedon) {
		this.generatedon = generatedon;
	}

	@Column(name = "zoneid")
	public String getZoneid() {
		return this.zoneid;
	}

	public void setZoneid(String zoneid) {
		this.zoneid = zoneid;
	}

	@Column(name = "generatedyear")
	public Date getGeneratedyear() {
		return this.generatedyear;
	}

	public void setGeneratedyear(Date generatedyear) {
		this.generatedyear = generatedyear;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaxGeneratedLogId))
			return false;
		TaxGeneratedLogId castOther = (TaxGeneratedLogId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getGeneratedby() == castOther.getGeneratedby()) || (this
						.getGeneratedby() != null
						&& castOther.getGeneratedby() != null && this
						.getGeneratedby().equals(castOther.getGeneratedby())))
				&& ((this.getGeneratedon() == castOther.getGeneratedon()) || (this
						.getGeneratedon() != null
						&& castOther.getGeneratedon() != null && this
						.getGeneratedon().equals(castOther.getGeneratedon())))
				&& ((this.getZoneid() == castOther.getZoneid()) || (this
						.getZoneid() != null && castOther.getZoneid() != null && this
						.getZoneid().equals(castOther.getZoneid())))
				&& ((this.getGeneratedyear() == castOther.getGeneratedyear()) || (this
						.getGeneratedyear() != null
						&& castOther.getGeneratedyear() != null && this
						.getGeneratedyear()
						.equals(castOther.getGeneratedyear())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37
				* result
				+ (getGeneratedby() == null ? 0 : this.getGeneratedby()
						.hashCode());
		result = 37
				* result
				+ (getGeneratedon() == null ? 0 : this.getGeneratedon()
						.hashCode());
		result = 37 * result
				+ (getZoneid() == null ? 0 : this.getZoneid().hashCode());
		result = 37
				* result
				+ (getGeneratedyear() == null ? 0 : this.getGeneratedyear()
						.hashCode());
		return result;
	}

}
