package com.silvassa.model;
// default package
// Generated Dec 15, 2016 5:54:25 PM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.silvassa.bean.PermissionBean;

/**
 * Usermaster generated by hbm2java
 */
@Entity
@Table(name = "usermaster", schema = "public")
public class Usermaster implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "usermaster_id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int usermasterId;
	@Column(name = "user_id")
	private String userId;
	@Column(name = "username")
	private String username;
        @Column(name = "pasword")
	private String pasword;
	@Column(name = "role_id")
	private String roleId;
	@Column(name = "status")
	private String status;
	@Column(name = "created_by")
	private String createdBy;
	
	@Column(name = "mobile")
	private Long mobile;
	@Column(name = "email")
	private String email;
	@Column(name = "address")
	private String address;
	@Column(name = "emp_id")
	private String empId;
         
         @Transient
        private String confirmPassword;

	

	@Transient
	private Date modifiedOn;
	@Transient
	private List<PermissionBean> permissionList;
	@Transient
	private Date createdOn;
	

	
	public Long getMobile() {
		return mobile;
	}
	public void setMobile(Long mobile) {
		this.mobile = mobile;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getEmpId() {
		return empId;
	}
	public void setEmpId(String empId) {
		this.empId = empId;
	}
	
	public int getUsermasterId() {
		return this.usermasterId;
	}
	public List<PermissionBean> getPermissionList() {
		return permissionList;
	}

	public void setPermissionList(List<PermissionBean> permissionList) {
		this.permissionList = permissionList;
	}
	public void setUsermasterId(int usermasterId) {
		this.usermasterId = usermasterId;
	}

	
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	
	public String getPasword() {
		return this.pasword;
	}

	public void setPasword(String pasword) {
		this.pasword = pasword;
	}

	
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

    public String getConfirmPassword() {
        return confirmPassword;
    }

    public void setConfirmPassword(String confirmPassword) {
        this.confirmPassword = confirmPassword;
    }

    @Override
    public String toString() {
        return "Usermaster{" + "usermasterId=" + usermasterId + ", userId=" + userId + ", username=" + username + ", pasword=" + pasword + ", roleId=" + roleId + ", status=" + status + ", createdBy=" + createdBy + ", mobile=" + mobile + ", email=" + email + ", address=" + address + ", empId=" + empId + ", confirmPassword=" + confirmPassword + ", modifiedOn=" + modifiedOn + ", permissionList=" + permissionList + ", createdOn=" + createdOn + '}';
    }


	

}
