package com.silvassa.model;
// default package
// Generated Dec 15, 2016 5:54:25 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Wardmaster generated by hbm2java
 */
@Entity
@Table(name = "ms_ward", schema = "public")
public class Wardmaster implements java.io.Serializable {

    
    @Column(name = "sno")
    private int sno;
    @Id
    @Column(name = "ward")
    private String ward;
    @Column(name = "display_name")
    private String displayName;
    @Column(name = "zone_associated")
    private String zoneAssociated;
    @Column(name = "status")
    private String status;

    /**
     * @return the sno
     */
    public int getSno() {
        return sno;
    }

    /**
     * @param sno the sno to set
     */
    public void setSno(int sno) {
        this.sno = sno;
    }

    /**
     * @return the ward
     */
    public String getWard() {
        return ward;
    }

    /**
     * @param ward the ward to set
     */
    public void setWard(String ward) {
        this.ward = ward;
    }

    /**
     * @return the displayName
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * @param displayName the displayName to set
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * @return the zoneAssociated
     */
    public String getZoneAssociated() {
        return zoneAssociated;
    }

    /**
     * @param zoneAssociated the zoneAssociated to set
     */
    public void setZoneAssociated(String zoneAssociated) {
        this.zoneAssociated = zoneAssociated;
    }

    /**
     * @return the status
     */
    public String getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "Wardmaster{" + "sno=" + sno + ", ward=" + ward + ", displayName=" + displayName + ", zoneAssociated=" + zoneAssociated + ", status=" + status + '}';
    }
    
    
    

}
