// default package
// Generated Dec 14, 2016 12:49:47 PM by Hibernate Tools 4.0.0

package com.silvassa.model;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Zonemaster generated by hbm2java
 */
@Entity
@Table(name = "zonemaster")
public class Zonemaster implements java.io.Serializable {

	private int zonemasterId;
	private String zoneId;
	private String zoneName;
	private String status;
	private String createdBy;
	private Date createdOn;
	private Date modifiedOn;

	public Zonemaster() {
	}

	public Zonemaster(int zonemasterId) {
		this.zonemasterId = zonemasterId;
	}

	public Zonemaster(int zonemasterId, String zoneId, String zoneName,
			String status, String createdBy, Date createdOn, Date modifiedOn) {
		this.zonemasterId = zonemasterId;
		this.zoneId = zoneId;
		this.zoneName = zoneName;
		this.status = status;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
	}

	@Id
	@Column(name = "zonemaster_id", unique = true, nullable = false)
	public int getZonemasterId() {
		return this.zonemasterId;
	}

	public void setZonemasterId(int zonemasterId) {
		this.zonemasterId = zonemasterId;
	}

	@Column(name = "zone_id")
	public String getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(String zoneId) {
		this.zoneId = zoneId;
	}

	@Column(name = "zone_name")
	public String getZoneName() {
		return this.zoneName;
	}

	public void setZoneName(String zoneName) {
		this.zoneName = zoneName;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on")
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_on")
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Zonemaster [zonemasterId=" + zonemasterId + ", zoneId="
				+ zoneId + ", zoneName=" + zoneName + ", status=" + status
				+ ", createdBy=" + createdBy + ", createdOn=" + createdOn
				+ ", modifiedOn=" + modifiedOn + "]";
	}

	
}
